### ISSUE TITLE
Wrong report

### ISSUE THREAD

**Issue by alfrix** [RobLoach/libretro-thumbnails-check#13]
Something wrong happened at 411a067d86 
I was checking Magnavox Odyssey 2 and noticed the report was completely wrong, then checked and it seems that all the individual reports have the same problem.

**Comment by alfrix** [comment]
Sorry sorry now i understand, nothing to see here

**Comment by RobLoach** [comment]
Yeah, I removed the `✓` to indicate a good check... Got a bit distracting. This makes it easier to find failures.
