### ISSUE TITLE
Separator

### ISSUE THREAD

**Issue by alfrix** [RobLoach/libretro-thumbnails-check#14]
This needs a separator like / or something between the marks, to improve legibility when the list is long and there are lonely markings in the middle

**Comment by RobLoach** [comment]
Have an example?

**Comment by alfrix** [comment]
Scroll through atari 2600
Wich one is missing?
![screenshot_20180401_164943](https://user-images.githubusercontent.com/1247237/38176852-e5647aea-35cc-11e8-94d8-ccf335dd365e.png)

It would be useful to have something like;
Frog (Demo)                             / X /    /     /
Another alternative is to have a B or S or T instead 
Frog (Demo)                             B
or maybe besides the X 
Frog (Demo)                             B-X
or all
Frog (Demo)                             / B-X /    /     /

I don't know, anything that helps without having to scroll up

**Comment by alfrix** [comment]
OR maybe the output should be Markdown (MD) in table format

**Comment by RobLoach** [comment]
Using a Markdown table is a great idea. Had it in markdown before, but the content was too long, GitHub wouldn't render it. Could try it out again.

**Comment by RobLoach** [comment]
Definitely easier to read now.

**Comment by RobLoach** [comment]
Thanks!
