### ISSUE TITLE
No entry on readme.md for Nintendo - Nintendo 64 

### ISSUE THREAD

**Issue by MarcoEstevez** [RobLoach/libretro-thumbnails-check#15]
Only shown "Nintendo - Nintendo 64DD" Is there any reason for not having it?

**Comment by RobLoach** [comment]
Very strange.

**Comment by RobLoach** [comment]
Looks like the last update to it was 5 months ago:
https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Nintendo%20-%20Nintendo%2064.txt

Very strange.

**Comment by MarcoEstevez** [comment]
Thanks @RobLoach, I see. 

I just wanted to see which Items are still missing.

**Comment by RobLoach** [comment]
Fixed!
