### ISSUE TITLE
I rescan directory of my games but problem

### ISSUE THREAD

**Issue by spotanjo3** [RobLoach/libretro-thumbnails-check#19]
I have 33 PSX games.. I rescan it and I only got 7 out of 33 PSX games! Why ?

**Comment by RobLoach** [comment]
Serial scanning is different than normal scanning. If they don't get into the playlist, I'd recommend using the playlist creator...
https://www.youtube.com/watch?v=RheJ3N_wP4w

Or the manual scanner.

**Comment by azoreseuropa** [comment]
I can try the manual scanner but never tried it before. I click Manual Scan and there are the names of the list so which one I select to scan my games ?

**Comment by spotanjo3** [comment]
I dont want the playlist creator, thanks.

I am frustrated. I put psx games in Retroarch like this: Retroarch>Downloads>PSX folder and I put one game just to test. 

It is Megaman Battle & Chase.bin and cue and rescan it. It didnt found it. Does that mean I have to type correct name ? Retroarch list said: Megaman Battle _ Chase (Europe) ?? 

And is PSX folder correct ? Or Sony - Playstation folder ? I am confused. Help ?

**Comment by RobLoach** [comment]
If you are frustrated by the scanner, and want full control over it, use this instead:
https://www.marcrobledo.com/retroarch-playlist-editor/

If you're frustred by the scanner, but don't want to use the playlist creator, that's on you.

Marco has done a great job with the online custom RetroArch playlist editor. Gives you full control over the files.

**Comment by azoreseuropa** [comment]
> If you are frustrated by the scanner, and want full control over it, use this instead:
> https://www.marcrobledo.com/retroarch-playlist-editor/
> 
> If you're frustred by the scanner, but don't want to use the playlist creator, that's on you.
> 
> Marco has done a great job with the online custom RetroArch playlist editor. Gives you full control over the files.

Great. I can do this..

I drag and drop all of them on it and there are core path to choose. Which one ? 

<img width="547" alt="Screen Shot 2020-02-24 at 4 18 37 PM" src="https://user-images.githubusercontent.com/16481778/75191959-5a600180-5721-11ea-962b-17f85e512fbb.png">


I am using retroarch for my Nintendo Switch.

**Comment by RobLoach** [comment]
Know what the default path is for Switch? We could add it in there.

In the mean time you could download the plyalist file and do a replace all.
