### ISSUE TITLE
.3ds entries

### ISSUE THREAD

**Issue by ghost** [RobLoach/libretro-thumbnails-check#26]
Any idea why there would ever be any entry ending in .3ds? Seems like being able to filter these out would reduce a significant chunk of this and make it easier to read.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/105944840/174837224-596c798f-dd85-40bf-b850-7abe8e33ecff.png">

**Comment by RobLoach** [comment]
Switched how the indexes are built.
